-- CREAR TABLAS

CREATE TABLE Materias (
ID INT IDENTITY (1,1) PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE Turnos  (
ID INT IDENTITY (1,1) PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE Alumnos (
ID INT IDENTITY (1,1) PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
MATERIA_ID INT NOT NULL,
TURNO_ID INT NOT NULL,
COMISION CHAR NOT NULL,
DEBE_CORRELATIVA BIT NOT NULL,
FOREIGN KEY (MATERIA_ID) REFERENCES Materias(ID),
FOREIGN KEY (TURNO_ID) REFERENCES Turnos(ID)
)

-- INSERTS

INSERT INTO Materias (NOMBRE) VALUES ('Backend')
INSERT INTO Materias (NOMBRE) VALUES ('Frontend')

INSERT INTO Turnos (NOMBRE) VALUES ('Mañana')
INSERT INTO Turnos (NOMBRE) VALUES ('Tarde')
INSERT INTO Turnos (NOMBRE) VALUES ('Noche')

INSERT INTO Alumnos VALUES ('Alicia Noemí Robles0',1 , 3, 'C', 0)
INSERT INTO Alumnos VALUES ('Mario Fortunato',2 , 2, 'A', 1)
INSERT INTO Alumnos VALUES ('Alcides Gioia',1 , 2, 'B', 0)
INSERT INTO Alumnos VALUES ('Julio Rodriguez',2 , 3, 'A', 1)



-- CONSULTAS

SELECT * FROM Alumnos

SELECT
a.ID,
a.NOMBRE,
m.NOMBRE AS MATERIA,
t.NOMBRE AS TURNO,
a.COMISION,
CASE
	WHEN DEBE_CORRELATIVA = 1 THEN 'Si'
	ELSE 'No'
	END AS DEBE_CORRELATIVA
FROM Alumnos a
JOIN
TURNOS t ON a.TURNO_ID = t.ID
JOIN
MATERIAS m ON a.MATERIA_ID = m.ID